import{Gauge,Mic2,Music2,Repeat2,SlidersHorizontal,Volume2}from'lucide-react';import{Toggle}from'./Controls';
type Pair=[boolean,boolean];type Volumes=[number,number];
export function VoicePractice({voices,volumes,singing,onVoices,onVolumes,onSinging}:{voices:Pair;volumes:Volumes;singing:0|1|2;onVoices:(v:Pair)=>void;onVolumes:(v:Volumes)=>void;onSinging:(v:0|1|2)=>void}){
 const mode=(m:'both'|'one'|'two')=>{onSinging(0);onVoices(m==='both'?[true,true]:m==='one'?[true,false]:[false,true])},sing=(v:1|2)=>{onSinging(v);onVoices(v===1?[false,true]:[true,false])};
 return <section className="card practice-card"><div className="card-heading"><Music2/><div><h2>Голоса</h2><p>Слушайте вместе или оставьте голос для самостоятельного пения</p></div></div><div className="voice-grid">{[0,1].map(i=><div className={`voice-strip voice-${i+1}`} key={i}><Toggle checked={voices[i]} onChange={checked=>{onSinging(0);onVoices(i===0?[checked,voices[1]]:[voices[0],checked])}} label={`Голос ${i+1}`}/><label className="volume"><Volume2 size={17}/><input aria-label={`Громкость голоса ${i+1}`} type="range" min="0" max="100" value={volumes[i]} onChange={e=>onVolumes(i===0?[+e.target.value,volumes[1]]:[volumes[0],+e.target.value])}/><b>{volumes[i]}%</b></label></div>)}</div>
 <div className="segmented three"><button className={voices[0]&&voices[1]&&!singing?'active':''} onClick={()=>mode('both')}>Оба голоса</button><button className={voices[0]&&!voices[1]&&!singing?'active':''} onClick={()=>mode('one')}>Только голос 1</button><button className={!voices[0]&&voices[1]&&!singing?'active':''} onClick={()=>mode('two')}>Только голос 2</button></div>
 <div className="sing-block"><div className="sing-label"><Mic2 size={19}/><b>Какой голос вы будете петь?</b></div><div className="sing-buttons"><button className={singing===1?'active':''} onClick={()=>sing(1)}>Я пою голос 1</button><button className={singing===2?'active':''} onClick={()=>sing(2)}>Я пою голос 2</button></div>{singing>0&&<div className="sing-message">Вы поёте голос {singing}. Звучит голос {singing===1?2:1}.</div>}</div></section>}
export function TempoPanel({bpm,originalBpm,onChange}:{bpm:number;originalBpm:number;onChange:(n:number)=>void}){const change=(n:number)=>onChange(Math.min(180,Math.max(40,Math.round(n))));return <section className="card"><div className="card-heading compact"><Gauge/><div><h2>Темп</h2><p>Исходный темп — {originalBpm} BPM</p></div><strong className="bpm">♩ = {bpm} <small>BPM</small></strong></div><input className="tempo-slider" aria-label="Темп" type="range" min="40" max="180" value={bpm} onChange={e=>change(+e.target.value)}/><div className="tempo-actions"><div>{[-10,-5,5,10].map(n=><button key={n} onClick={()=>change(bpm+n)}>{n>0?'+'+n:n}</button>)}</div><div>{[50,75,100,125].map(p=><button key={p} className={bpm===Math.round(originalBpm*p/100)?'active':''} onClick={()=>change(originalBpm*p/100)}>{p}%</button>)}</div></div></section>}
type SettingsProps={metronome:boolean;countIn:number;repeat:boolean;loop:{enabled:boolean;start:number;end:number};measureCount:number;acceleration:{start:number;step:number;end:number};onMetronome:(v:boolean)=>void;onCountIn:(v:number)=>void;onRepeat:(v:boolean)=>void;onLoop:(v:{enabled:boolean;start:number;end:number})=>void;onAcceleration:(v:{start:number;step:number;end:number})=>void;onNextTempo:()=>void};
export function SettingsPanel(p:SettingsProps){const{metronome,countIn,repeat,loop,measureCount,acceleration}=p;return <section className="card settings-card"><div className="card-heading"><SlidersHorizontal/><div><h2>Настройки занятия</h2><p>Отсчёт, метроном и работа над фрагментом</p></div></div><div className="settings-grid"><div className="setting-group"><Toggle checked={metronome} onChange={p.onMetronome} label="Метроном"/><Toggle checked={repeat} onChange={p.onRepeat} label="Повтор всего произведения"/></div><div className="setting-group"><label className="field-label">Отсчёт перед началом<select value={countIn} onChange={e=>p.onCountIn(+e.target.value)}><option value="0">Нет</option><option value="1">1 такт</option><option value="2">2 такта</option></select></label></div></div>
<div className="loop-box"><div className="loop-title"><Repeat2 size={18}/><b>Повтор фрагмента</b></div><div className="loop-fields"><label>Начальный такт<input type="number" min="1" max={measureCount} value={loop.start} onChange={e=>p.onLoop({...loop,start:Math.max(1,Math.min(measureCount,+e.target.value))})}/></label><label>Конечный такт<input type="number" min="1" max={measureCount} value={loop.end} onChange={e=>p.onLoop({...loop,end:Math.max(1,Math.min(measureCount,+e.target.value))})}/></label><button className={loop.enabled?'active':''} onClick={()=>p.onLoop({...loop,enabled:!loop.enabled})}>{loop.enabled?'Повторяются такты '+loop.start+'–'+loop.end:'Повторять такты '+loop.start+'–'+loop.end}</button></div></div>
<details><summary>Постепенное ускорение</summary><div className="accel-grid"><label>Начальный темп<input type="number" min="40" max="180" value={acceleration.start} onChange={e=>p.onAcceleration({...acceleration,start:+e.target.value})}/></label><label>Шаг<input type="number" min="1" max="30" value={acceleration.step} onChange={e=>p.onAcceleration({...acceleration,step:+e.target.value})}/></label><label>Конечный темп<input type="number" min="40" max="180" value={acceleration.end} onChange={e=>p.onAcceleration({...acceleration,end:+e.target.value})}/></label><button onClick={p.onNextTempo}>Следующий темп +{acceleration.step}</button></div></details></section>}
